services:

  ExampleApp:
    class: processor.ExampleApp
    arguments: [$MongoClient]

  MongoClient:
    class: pymongo.MongoClient
    arguments: ['%mongo_host%', '%mongo_port%']

chains:
  - ExampleApp