services:

  ExampleApp:
    class: processor.ExampleApp
    arguments: [$Mongodb]

  Mongodb:
    class: ank.utils.my_mongo.Mongodb
    arguments: ['%mongo_db%', '%mongo_col%']

chains:
  - ExampleApp