services:
  ExampleApp:
    class: processor.ExampleApp
    arguments: ~

  RabbitmqConsumer:
    class: apps.rabbitmq_consumer.RabbitmqConsumer
    arguments:
      uri: '%queue_consumer_uri%'
      queue: '%queue_consumer_name%'

  LogHandle:
    class: apps.log_app.LogApp
    arguments: ~

  RabbitmqProducer:
    class: app.rabbitmq_consumer.RabbitmqProducer
    arguments:
      uri: '%queue_producer_uri%'
      exchange: '%exchange_producer_name%'
      routing_key: '%routing_key_name%'

chains:
  - RabbitmqConsumer
  - LogApp
  - ExampleApp
  - RabbitmqProducer